language: go

go_import_path: github.com/stellar/kelp

services:
- docker

go:
- "1.10.x"
- "1.11.x"
- "1.12.x"

before_install:
- curl https://glide.sh/get | sh
- docker run -p 3000:3000 -d franzsee/ccxt-rest

install:
- glide install

script:
- ./scripts/build.sh
- ./bin/kelp version
- go test -tags dev --short ./...
